CREATE DATABASE `DB_STPYTHON`;

USE DB_STPYTHON;


-- =======================
-- TABELA USUARIO
-- =======================

CREATE TABLE IF NOT EXISTS `DB_STPYTHON`.`USUARIO` (
  `ID_USUARIO`       INT          NOT NULL AUTO_INCREMENT,
  `CPF_USUARIO`      VARCHAR(11)  NOT NULL,
  `NOME_USUARIO`     VARCHAR(250) NOT NULL,
  `RG_USUARIO`       VARCHAR(9)   NOT NULL,
  `EMAIL_USUARIO`    VARCHAR(250) NULL,
  `SENHA_USUARIO`    VARCHAR(500) NOT NULL,
  `STATUS_USUARIO`   TINYINT(1)   NOT NULL,
  `TELEFONE_USUARIO` VARCHAR(9)   NOT NULL,
  PRIMARY KEY (`ID_USUARIO`)
);
-- ======================
-- VALORES PADRÃO 
-- =====================
INSERT INTO USUARIO
(
	 CPF_USUARIO 
	,NOME_USUARIO
	,RG_USUARIO
	,EMAIL_USUARIO
	,SENHA_USUARIO
	,STATUS_USUARIO
    ,TELEFONE_USUARIO
) 
VALUES ('12345678910', 'Admin', '12345567','admin@email.com','1234','1','123456789');



CREATE TABLE IF NOT EXISTS `DB_STPYTHON`.`ENDERECO` (
  `ID_ENDERECO`     INT NOT NULL AUTO_INCREMENT,
  `CEP_ENDERECO`    INT  NULL,
  `BAIRRO_ENDERECO` VARCHAR(250)  NULL,
  `CIDADE_ENDERECO` VARCHAR(250)  NULL,
  `UF_ENDERECO`     CHAR(2) NULL,
  `ID_USUARIO`      INT NULL,
  PRIMARY KEY (`ID_ENDERECO`),
  CONSTRAINT `fk_ENDERECO_USUARIO1`  FOREIGN KEY (`ID_USUARIO`) REFERENCES `DB_STPYTHON`.`USUARIO` (`ID_USUARIO`)
  );

INSERT INTO `DB_STPYTHON`.`ENDERECO` 
(
    CEP_ENDERECO, 
    BAIRRO_ENDERECO,
    CIDADE_ENDERECO,
    UF_ENDERECO,
    ID_USUARIO    
)
VALUES ('12345678', 'BAIRRO ADM', 'CIDADE ADM', 'SP', '1');
